reward_log_name: meta_math_binary

reward_fns:
  _target_: hydra_utils.wrap_as_list
  meta_math_exact_match_reward:
    _target_: hydra_utils.load_function
    path: trainers.reward_functions.meta_math_exact_match_reward
